services:
  ev-tracker:
    image: 19121412/ev-tracker:latest
    container_name: ev-tracker
    restart: unless-stopped
    ports:
      - "8054:8080"
    volumes:
      - /mnt/user/appdata/ev-tracker:/data
      - /var/run/docker.sock:/var/run/docker.sock  # für Auto-Update
    environment:
      DATA_DIR: "/data"
      TZ: "Europe/Berlin"
