"""Central version — read once at import time, cached as module-level constants.

Priority order for each field:
  1. Environment variable (set by Docker build-args at image build time)
  2. /app/build-info.json  (generated by GitHub Actions before docker build)
  3. /app/version.json     (static fallback committed to repo)
  4. Hardcoded default
"""
import json
import os
from pathlib import Path

_here = Path(__file__).parent

# version.json — static fallback values committed to the repo
_vfile = next(
    (p for p in (_here / "version.json", _here.parent / "version.json") if p.exists()),
    None,
)
try:
    _vdata = json.loads(_vfile.read_text())
except Exception:
    _vdata = {}

# build-info.json — generated by CI at build time; not present in local/dev builds
_bfile = next(
    (p for p in (_here / "build-info.json", _here.parent / "build-info.json") if p.exists()),
    None,
)
try:
    _bdata = json.loads(_bfile.read_text()) if _bfile else {}
except Exception:
    _bdata = {}

# Legacy alias kept so existing code that does `_data = version._data` still works.
_data = _vdata


def _env_or(key: str, fallback: str) -> str:
    """Return env var if set and not 'unknown', else fallback."""
    v = os.getenv(key, "").strip()
    return v if v and v != "unknown" else fallback


def _bi(key: str, fallback: str = "") -> str:
    """Read a field from build-info.json, fall through if missing/empty/unknown."""
    v = str(_bdata.get(key, "")).strip()
    return v if v and v != "unknown" else fallback


# ── Main version fields: ENV > build-info.json > version.json > default ──────
APP_VERSION = _env_or("EV_TRACKER_VERSION",  _bi("version",   _vdata.get("version",   "unknown")))
BUILD_DATE  = _env_or("EV_TRACKER_BUILD",     _bi("build_utc", _vdata.get("build",     "")))
CHANNEL     = _env_or("EV_TRACKER_CHANNEL",   _bi("channel",   _vdata.get("channel",   "stable")))
GIT_COMMIT  = _env_or("EV_TRACKER_COMMIT",    _bi("commit",    _vdata.get("commit",    "")))
GIT_BRANCH  = _env_or("EV_TRACKER_BRANCH",    _bi("branch",    _vdata.get("branch",    "")))
IMAGE_TAG   = _env_or("EV_TRACKER_IMAGE_TAG", _bi("image_tag", _vdata.get("image_tag", "")))

# ── Derived ───────────────────────────────────────────────────────────────────
COMMIT_SHORT = GIT_COMMIT[:8] if GIT_COMMIT else ""

# Explicit UTC alias — BUILD_DATE is always a UTC ISO string when set by CI
BUILD_DATE_UTC = BUILD_DATE

# Extra fields only available from build-info.json (no ENV var equivalent)
BUILD_SOURCE  = _bi("build_source",  "local")
GITHUB_RUN_ID = _bi("github_run_id", "")
GITHUB_REF    = _bi("github_ref",    "")

ASSET_VERSION = APP_VERSION + "-" + (COMMIT_SHORT or BUILD_DATE.replace("-", "") or "local")

# ── Display fallbacks — never empty, shown in UI and /api/update-info ─────────
DISPLAY_BRANCH       = GIT_BRANCH   or "local/source"
DISPLAY_COMMIT       = GIT_COMMIT   or "unknown"
DISPLAY_COMMIT_SHORT = COMMIT_SHORT or "unknown"
DISPLAY_IMAGE_TAG    = IMAGE_TAG    or "unknown"

CHANGELOG = []  # Legacy — kept for import compatibility
